" My vimrc

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
 
" Make backspace behave in a sane manner.
set backspace=indent,eol,start
 
" Switch syntax highlighting on
syntax on
 
" Enable file type detection and do language-dependent indenting.
filetype plugin indent on

" Mouse scrolling in all modes
set mouse=a

" show auto complete menus
set wildmenu

" Line numbering
set relativenumber
set number

" Command window height
set cmdheight=2

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" Markdown support (not Modula-2)
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
